name: Prash' Universe
favicon: null
layout_spectrum: 0.23204084439203143
typography_spectrum: 0.8975378058385104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6601204879116267
  lightness: 0.03876678133383393
  saturation: 0.9761668741703033
  rhythmicContrast: 0.27952480339445174
purpose: []
